[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'python39Packages.numpy', 'python39Packages.scikit-learn']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'cd src/backend && uvicorn main:app --host 0.0.0.0 --port $PORT' 